---
global:
  host1_username: root
cases:
- tt_members: profesor
  tt_moodle_id: profesor@moodle.id
  script: ruby /vagrant/profesor.rb
  host1_ip: 192.168.1.140
  host1_port: 2241
  host1_password: vagrant
