---
global:
  listar:
    - "nobody,65534,/usr/sbin/nologin,nobody"
  consultar:
    - Usuario, root
    - UID, 0
    - GID, 0
    - Shell, /bin/bash
    - HOME, /root
cases:
- tt_members: profesor
  tt_moodle_id: profesor@moodle.id
  host1_ip: localhost
  cmd:
    - "docker run -it --rm --name"
    - usermin
    - "-v /home/david/proy/repos/teuton.d/teuton-tests/temp/usermin:/opt"
    - "-w /opt"
    - "ruby:latest"
    - "ruby profesor.rb"
