---
global:
  listar:
    - "nobody,65534,/usr/sbin/nologin,nobody"
  consultar:
    - Usuario, root
    - UID, 0
    - GID, 0
    - Shell, /bin/bash
    - HOME, /root
cases:
- tt_members: profesor
  tt_moodle_id: profesor@moodle.id
  cmd: "ruby temp/usermin/profesor.rb"
  host1_ip: localhost
