---
global:
  cmd: es/sistemas.3/scripting/usermin/vagrant/demo.rb
  listar:
    - "nobody,65534,/bin/bash,nobody"
    - "quigon,1000,/bin/zsh,quigon"
    - "profesor,1001,/bin/bash,"
  consultar:
    - root
    - 0
    - 0
    - /bin/bash
    - /root
cases:
- tt_members: MEMBERS
  tt_moodle_id: MOODLE_ID
