---
global:
  listar:
    - "vader1,1000,/bin/bash,teuton"
    - "obiwan2,1001,/bin/bash,teuton"
    - "yoda3,1002,/bin/bash,teuton"
  consultar:
    - Usuario, obiwan2
    - UID, 1001
    - GID, 100
    - Shell, /bin/bash
    - HOME, /home/obiwan
cases:
- tt_members: profesor
  tt_moodle_id: profesor@moodle.id
  host1_ip: localhost
  cmd:
    - "docker run -it --rm --name"
    - usermin
    - "-v /home/david/proy/repos/teuton.d/teuton-tests/temp/usermin:/opt"
    - "-v /home/david/proy/repos/teuton.d/teuton-tests/temp/etc:/etc"
    - "-w /opt"
    - "ruby:latest "
  script: " ruby profesor.rb"
