---
global:
  cmd: /vagrant/usermine.rb
  listar:
    - nobody,65534,/usr/sbin/nologin,nobody
    - vagrant,1000,/bin/bash,vagrant,,,
  consultar:
    - root
    - 0
    - 0
    - /bin/bash
    - /root
cases:
- tt_members: profesor
  tt_moodle_id: profesor@moodle.id
  host1_ip: 192.168.1.140
  host1_port: 2241
  host1_username: vagrant
  host1_password: vagrant
