---
:global:
:cases:
- :tt_members: vagrant-debian
  :host_ip: 192.168.1.42
  :host_port: 2241
  :host_username: vagrant
  :host_password: vagrant
  :hostname: vagrant-debian
- :tt_members: pc25
  :host_ip: 172.18.25.0
  :host_username: super
  :host_password: trabajarenEQUIPO
  :hostname: ubuntu
