---
global:
  host_ip: localhost
  gns3server_ip: localhost
cases:
- tt_members: Student1
  project_file: lab.gns3
  project_dir: project
  project_path: project/lab.gns3
  pc1_ip: 192.168.1.201
  pc2_ip: 192.168.1.202
