---
global:
cases:
- tt_members: Student1
  host_ip: localhost
  project_file: lab.gns3
  project_dir: project
  project_path: project/lab.gns3
  gns3server_ip: localhost
  pc1_ip: 192.168.1.201
  pc2_ip: 192.168.1.202
- tt_members: Student2
  host_ip: 10.0.0.2
  project_file: lab.gns3
  project_dir: project
  project_path: project/lab.gns3
  gns3server_ip: localhost
  pc1_ip: 192.168.1.201
  pc2_ip: 192.168.1.202
