---
:global:
  :gateway_ip: 192.168.1.1
:cases:
- :tt_members: Test OpenSUSE MV
  :username: vagrant
  :host1_hostname: s-node
  :host1_ip: 192.168.1.115
  :host1_username: vagrant
  :host1_password: vagrant
