---
:global:
  :opensuse_username: root
  :domain: curso201718
:cases:
- :tt_members: VALUE
  :number: '19'
  :win7_ip: 172.19.19.11
  :ws2008_ip: 172.19.19.21
  :opensuse_ip: 172.19.19.51
  :opensuse_password: VALUE
  :firstname: VALUE
  :lastname1: VALUE
  :lastname2: VALUE
