---
:global:
  :host_username: super
  :host_password: trabajarenEQUIPO
:cases:
- :tt_members: pc01
  :host_ip: 172.18.1.0
- :tt_members: pc02
  :host_ip: 172.18.2.0
- :tt_members: pc03
  :host_ip: 172.18.3.0
- :tt_members: pc04
  :host_ip: 172.18.4.0
- :tt_members: pc05
  :host_ip: 172.18.5.0
- :tt_members: pc06
  :host_ip: 172.18.6.0
- :tt_members: pc07
  :host_ip: 172.18.7.0
- :tt_members: pc08
  :host_ip: 172.18.8.0
- :tt_members: pc09
  :host_ip: 172.18.9.0
- :tt_members: pc10
  :host_ip: 172.18.10.0
- :tt_members: pc11
  :host_ip: 172.18.11.0
- :tt_members: pc12
  :host_ip: 172.18.12.0
- :tt_members: pc13
  :host_ip: 172.18.13.0
- :tt_members: pc14
  :host_ip: 172.18.14.0
- :tt_members: pc15
  :host_ip: 172.18.15.0
- :tt_members: pc16
  :host_ip: 172.18.16.0
- :tt_members: pc17
  :host_ip: 172.18.17.0
- :tt_members: pc18
  :host_ip: 172.18.18.0
- :tt_members: pc19
  :host_ip: 172.18.19.0
- :tt_members: pc20
  :host_ip: 172.18.20.0
- :tt_members: pc21
  :host_ip: 172.18.21.0
- :tt_members: pc22
  :host_ip: 172.18.22.0
- :tt_members: pc23
  :host_ip: 172.18.23.0
- :tt_members: pc24
  :host_ip: 172.18.24.0
- :tt_members: pc25
  :host_ip: 172.18.25.0
- :tt_members: pc26
  :host_ip: 172.18.26.0
- :tt_members: pc27
  :host_ip: 172.18.27.0
- :tt_members: pc28
  :host_ip: 172.18.28.0
- :tt_members: pc29
  :host_ip: 172.18.29.0
- :tt_members: pc30
  :host_ip: 172.18.30.0
