---
:global:
  :gateway_ip: 172.18.0.1
  :host1_protocol: telnet
  :host1_domain: curso1920
  :host1_productname: "Windows 7 Professional"
:cases:
- :tt_members: Test Windows7
  :tt_skip: false
  :username: teuton
  :lastname: IDP
  :number: "01"
  :host1_ip: 192.168.1.111
  :host1_username: teuton
  :host1_password: profesor
  :host1_protocol: ssh
