---
:global:
  :linux_ip: 192.168.1.106
  :windows_ip: 192.168.1.114
:cases:
- :tt_members: Test Connections
  :host1_username: root
  :host1_password: profesor
  :host2_username: profesor
  :host2_password: profesor
  :host3_username: root
  :host3_password: profesor
  :host3_protocol: telnet
  :host4_username: profesor
  :host4_password: profesor
  :host4_protocol: telnet
  :win1_username: administrador
  :win1_password: profesorFP2018
  :win2_username: profesor
  :win2_password: sayonaraBABY2018
  :win3_username: administrador
  :win3_password: profesorFP2018
  :win3_protocol: telnet
  :win4_username: profesor
  :win4_password: sayonaraBABY2018
  :win4_protocol: telnet
