---
global:
  tt_sequence: true
  cmd:
    - docker run -it --rm --name
    - usermin_FOLDER
    - "-v PWD/var/usermin/temp/FOLDER/etc:/etc"
    - "-v PWD/var/usermin/temp/FOLDER/opt:/opt"
    - "-w /opt"
    - "ruby:latest "
  script: " bash usermin.sh"
  nuevo:
    - "vader1"
    - "obiwan2"
  listar:
    - "vader1,1000,/bin/bash,teuton"
    - "obiwan2,1001,/bin/bash,teuton"
  consultar:
    - Usuario, obiwan2
    - UID, 1001
    - GID, 100
    - Shell, /bin/bash
    - HOME, /home/obiwan
  eliminar:
    - "obiwan2"
cases:
- tt_members: profesor
  tt_moodle_id: profesor@moodle.id
  host1_ip: localhost
  folder: profesor
  script: " ruby profesor.rb"
