---
:global:
  :gateway: 192.168.1.1
  :dns: 8.8.4.4
  :domain: curso1516
  :windows1_username: sysadmingame  
  :windows1_protocol: telnet
:cases:
- :tt_members: Obiwan
  :firstname: obiwan
  :lastname: kenobi
  :windows1_hostname: ABR2016
  :windows1_ip: 192.168.1.111
  :windows1_password: profesor
